
###
post  http://localhost:4300/api/cetificate
Content-Type: application/json

{
   
    
    "employeecode": "121",
"FileName":"certificate.jpg",
"FileData":"iVBORw0KGgoAAAANSUhE",
"UploadDate":"sdfs"
 
}