
###
post  http://localhost:4300/api/regularization
Content-Type: application/json

{
   
    "RegularizationType": "miss punch in ",
    "RegularizationDate": "22-02-2020",
    "RegularizationPunchInTime": "11:11:11",
    "employeecode": "121",
    "RegularizationPunchOutTime":"11:11:11",
    "Reason":"test",
    "RegularizationStatus":"Pending"
 
}